run pgm = hwynet
	neti = D:\mtc_travel_model\2010_nonode_TEST\INPUT\hwy\freeflow_undamaged.NET
	neto = D:\mtc_travel_model\2010_nonode_TEST\INPUT\hwy\freeflow4603extensive.net
	CTIM = FFT 
	if (a = 7846 & b = 7849) CAPCLASS = 62
	if (a = 7846 & b = 7849) SPDCLASS = 62
	if (a = 7995 & b = 7848) CAPCLASS = 62
	if (a = 7995 & b = 7848) SPDCLASS = 62
	if (a = 9643 & b = 9637) CAPCLASS = 62
	if (a = 9643 & b = 9637) SPDCLASS = 62
endrun 
