run pgm = hwynet
	neti = D:\mtc_travel_model\2010_nonode_TEST\INPUT\hwy\freeflow_undamaged.NET
	neto = D:\mtc_travel_model\2010_nonode_TEST\INPUT\hwy\freeflow5807extensive.net
	CTIM = FFT 
	if (a = 8282 & b = 8284) CAPCLASS = 62
	if (a = 8282 & b = 8284) SPDCLASS = 62
	if (a = 8284 & b = 8282) CAPCLASS = 62
	if (a = 8284 & b = 8282) SPDCLASS = 62
	if (a = 8473 & b = 14506) CAPCLASS = 62
	if (a = 8473 & b = 14506) SPDCLASS = 62
endrun 
