run pgm = hwynet
	neti = D:\mtc_travel_model\2010_nonode_TEST\INPUT\hwy\freeflow_undamaged.NET
	neto = D:\mtc_travel_model\2010_nonode_TEST\INPUT\hwy\freeflow5225extensive.net
	CTIM = FFT 
	if (a = 5781 & b = 5788) CAPCLASS = 62
	if (a = 5781 & b = 5788) SPDCLASS = 62
	if (a = 5779 & b = 5780) CAPCLASS = 62
	if (a = 5779 & b = 5780) SPDCLASS = 62
	if (a = 5780 & b = 5779) CAPCLASS = 62
	if (a = 5780 & b = 5779) SPDCLASS = 62
endrun 
