run pgm = hwynet
	neti = D:\mtc_travel_model\2010_nonode_TEST\INPUT\hwy\freeflow_undamaged.NET
	neto = D:\mtc_travel_model\2010_nonode_TEST\INPUT\hwy\freeflow1417extensive.net
	CTIM = FFT 
	if (a = 4188 & b = 4180) CAPCLASS = 62
	if (a = 4188 & b = 4180) SPDCLASS = 62
	if (a = 15855 & b = 8675) CAPCLASS = 62
	if (a = 15855 & b = 8675) SPDCLASS = 62
	if (a = 8009 & b = 1640) CAPCLASS = 62
	if (a = 8009 & b = 1640) SPDCLASS = 62
endrun 
