run pgm = hwynet
	neti = D:\mtc_travel_model\2010_nonode_TEST\INPUT\hwy\freeflow_undamaged.NET
	neto = D:\mtc_travel_model\2010_nonode_TEST\INPUT\hwy\freeflow10667extensive.net
	CTIM = FFT 
	if (a = 6366 & b = 6367) CAPCLASS = 62
	if (a = 6366 & b = 6367) SPDCLASS = 62
	if (a = 6367 & b = 6366) CAPCLASS = 62
	if (a = 6367 & b = 6366) SPDCLASS = 62
	if (a = 1863 & b = 1692) CAPCLASS = 62
	if (a = 1863 & b = 1692) SPDCLASS = 62
endrun 
