run pgm = hwynet
	neti = D:\mtc_travel_model\2010_nonode_TEST\INPUT\hwy\freeflow_undamaged.NET
	neto = D:\mtc_travel_model\2010_nonode_TEST\INPUT\hwy\freeflow2159extensive.net
	CTIM = FFT 
	if (a = 5917 & b = 5907) CAPCLASS = 62
	if (a = 5917 & b = 5907) SPDCLASS = 62
	if (a = 5916 & b = 5918) CAPCLASS = 62
	if (a = 5916 & b = 5918) SPDCLASS = 62
	if (a = 5918 & b = 5916) CAPCLASS = 62
	if (a = 5918 & b = 5916) SPDCLASS = 62
endrun 
