run pgm = hwynet
	neti = D:\mtc_travel_model\2010_nonode_TEST\INPUT\hwy\freeflow_undamaged.NET
	neto = D:\mtc_travel_model\2010_nonode_TEST\INPUT\hwy\freeflow1442extensive.net
	CTIM = FFT 
	if (a = 4758 & b = 5117) CAPCLASS = 62
	if (a = 4758 & b = 5117) SPDCLASS = 62
	if (a = 20108 & b = 9401) CAPCLASS = 62
	if (a = 20108 & b = 9401) SPDCLASS = 62
	if (a = 5694 & b = 5695) CAPCLASS = 62
	if (a = 5694 & b = 5695) SPDCLASS = 62
endrun 
