run pgm = hwynet
	neti = D:\mtc_travel_model\2010_nonode_TEST\INPUT\hwy\freeflow_undamaged.NET
	neto = D:\mtc_travel_model\2010_nonode_TEST\INPUT\hwy\freeflow4631extensive.net
	CTIM = FFT 
	if (a = 8477 & b = 8593) CAPCLASS = 62
	if (a = 8477 & b = 8593) SPDCLASS = 62
	if (a = 8586 & b = 8592) CAPCLASS = 62
	if (a = 8586 & b = 8592) SPDCLASS = 62
	if (a = 8592 & b = 8586) CAPCLASS = 62
	if (a = 8592 & b = 8586) SPDCLASS = 62
endrun 
