run pgm = hwynet
	neti = D:\mtc_travel_model\2010_nonode_TEST\INPUT\hwy\freeflow_undamaged.NET
	neto = D:\mtc_travel_model\2010_nonode_TEST\INPUT\hwy\freeflow9890extensive.net
	CTIM = FFT 
	if (a = 15855 & b = 8675) CAPCLASS = 62
	if (a = 15855 & b = 8675) SPDCLASS = 62
	if (a = 8484 & b = 8485) CAPCLASS = 62
	if (a = 8484 & b = 8485) SPDCLASS = 62
	if (a = 8485 & b = 8484) CAPCLASS = 62
	if (a = 8485 & b = 8484) SPDCLASS = 62
endrun 
