run pgm = hwynet
	neti = D:\mtc_travel_model\2010_nonode_TEST\INPUT\hwy\freeflow_undamaged.NET
	neto = D:\mtc_travel_model\2010_nonode_TEST\INPUT\hwy\freeflow9880extensive.net
	CTIM = FFT 
	if (a = 12251 & b = 8594) CAPCLASS = 62
	if (a = 12251 & b = 8594) SPDCLASS = 62
	if (a = 8792 & b = 12252) CAPCLASS = 62
	if (a = 8792 & b = 12252) SPDCLASS = 62
	if (a = 8481 & b = 8480) CAPCLASS = 62
	if (a = 8481 & b = 8480) SPDCLASS = 62
endrun 
