run pgm = hwynet
	neti = D:\mtc_travel_model\2010_nonode_TEST\INPUT\hwy\freeflow_undamaged.NET
	neto = D:\mtc_travel_model\2010_nonode_TEST\INPUT\hwy\freeflow1387extensive.net
	CTIM = FFT 
	if (a = 15855 & b = 8675) CAPCLASS = 62
	if (a = 15855 & b = 8675) SPDCLASS = 62
	if (a = 6213 & b = 6463) CAPCLASS = 62
	if (a = 6213 & b = 6463) SPDCLASS = 62
	if (a = 6521 & b = 238) CAPCLASS = 62
	if (a = 6521 & b = 238) SPDCLASS = 62
endrun 
