run pgm = hwynet
	neti = D:\mtc_travel_model\2010_nonode_TEST\INPUT\hwy\freeflow_undamaged.NET
	neto = D:\mtc_travel_model\2010_nonode_TEST\INPUT\hwy\freeflow4889extensive.net
	CTIM = FFT 
	if (a = 10016 & b = 8597) CAPCLASS = 62
	if (a = 10016 & b = 8597) SPDCLASS = 62
	if (a = 8469 & b = 8784) CAPCLASS = 62
	if (a = 8469 & b = 8784) SPDCLASS = 62
	if (a = 8469 & b = 8470) CAPCLASS = 62
	if (a = 8469 & b = 8470) SPDCLASS = 62
endrun 
