run pgm = hwynet
	neti = D:\mtc_travel_model\2010_nonode_TEST\INPUT\hwy\freeflow_undamaged.NET
	neto = D:\mtc_travel_model\2010_nonode_TEST\INPUT\hwy\freeflow375extensive.net
	CTIM = FFT 
	if (a = 11881 & b = 11880) CAPCLASS = 62
	if (a = 11881 & b = 11880) SPDCLASS = 62
	if (a = 11865 & b = 11866) CAPCLASS = 62
	if (a = 11865 & b = 11866) SPDCLASS = 62
	if (a = 11879 & b = 11878) CAPCLASS = 62
	if (a = 11879 & b = 11878) SPDCLASS = 62
endrun 
