run pgm = hwynet
	neti = D:\mtc_travel_model\2010_nonode_TEST\INPUT\hwy\freeflow_undamaged.NET
	neto = D:\mtc_travel_model\2010_nonode_TEST\INPUT\hwy\freeflow11107extensive.net
	CTIM = FFT 
	if (a = 2069 & b = 2070) CAPCLASS = 62
	if (a = 2069 & b = 2070) SPDCLASS = 62
	if (a = 6465 & b = 6471) CAPCLASS = 62
	if (a = 6465 & b = 6471) SPDCLASS = 62
	if (a = 6471 & b = 6465) CAPCLASS = 62
	if (a = 6471 & b = 6465) SPDCLASS = 62
endrun 
