run pgm = hwynet
	neti = D:\mtc_travel_model\2010_nonode_TEST\INPUT\hwy\freeflow_undamaged.NET
	neto = D:\mtc_travel_model\2010_nonode_TEST\INPUT\hwy\freeflow6268extensive.net
	CTIM = FFT 
	if (a = 4150 & b = 4187) CAPCLASS = 62
	if (a = 4150 & b = 4187) SPDCLASS = 62
	if (a = 4187 & b = 4150) CAPCLASS = 62
	if (a = 4187 & b = 4150) SPDCLASS = 62
	if (a = 8009 & b = 1640) CAPCLASS = 62
	if (a = 8009 & b = 1640) SPDCLASS = 62
endrun 
