run pgm = hwynet
	neti = D:\mtc_travel_model\2010_nonode_TEST\INPUT\hwy\freeflow_undamaged.NET
	neto = D:\mtc_travel_model\2010_nonode_TEST\INPUT\hwy\freeflow5392extensive.net
	CTIM = FFT 
	if (a = 2936 & b = 4123) CAPCLASS = 62
	if (a = 2936 & b = 4123) SPDCLASS = 62
	if (a = 4115 & b = 2899) CAPCLASS = 62
	if (a = 4115 & b = 2899) SPDCLASS = 62
	if (a = 4109 & b = 4121) CAPCLASS = 62
	if (a = 4109 & b = 4121) SPDCLASS = 62
endrun 
