run pgm = hwynet
	neti = D:\mtc_travel_model\2010_nonode_TEST\INPUT\hwy\freeflow_undamaged.NET
	neto = D:\mtc_travel_model\2010_nonode_TEST\INPUT\hwy\freeflow10171extensive.net
	CTIM = FFT 
	if (a = 4178 & b = 4172) CAPCLASS = 62
	if (a = 4178 & b = 4172) SPDCLASS = 62
	if (a = 4208 & b = 4591) CAPCLASS = 62
	if (a = 4208 & b = 4591) SPDCLASS = 62
	if (a = 4634 & b = 4205) CAPCLASS = 62
	if (a = 4634 & b = 4205) SPDCLASS = 62
endrun 
