run pgm = hwynet
	neti = D:\mtc_travel_model\2010_nonode_TEST\INPUT\hwy\freeflow_undamaged.NET
	neto = D:\mtc_travel_model\2010_nonode_TEST\INPUT\hwy\freeflow1992extensive.net
	CTIM = FFT 
	if (a = 8594 & b = 8478) CAPCLASS = 62
	if (a = 8594 & b = 8478) SPDCLASS = 62
	if (a = 8586 & b = 8592) CAPCLASS = 62
	if (a = 8586 & b = 8592) SPDCLASS = 62
	if (a = 8592 & b = 8586) CAPCLASS = 62
	if (a = 8592 & b = 8586) SPDCLASS = 62
endrun 
