run pgm = hwynet
	neti = D:\mtc_travel_model\2010_nonode_TEST\INPUT\hwy\freeflow_undamaged.NET
	neto = D:\mtc_travel_model\2010_nonode_TEST\INPUT\hwy\freeflow210extensive.net
	CTIM = FFT 
	if (a = 4180 & b = 4181) CAPCLASS = 62
	if (a = 4180 & b = 4181) SPDCLASS = 62
	if (a = 4178 & b = 4172) CAPCLASS = 62
	if (a = 4178 & b = 4172) SPDCLASS = 62
	if (a = 4183 & b = 4177) CAPCLASS = 62
	if (a = 4183 & b = 4177) SPDCLASS = 62
endrun 
